todoproject/todoapp/urls.py
from .import views
from django.urls import path
app_name='todoapp'
urlpatterns = [
    path('',views.add,name='add'),
    path('details',views.details,name='details'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('classviewhome/',views.TaskListview.as_view(),name='classviewhome'),
    path('classviewdetails/<int:pk>/',views.TaskDetailview.as_view(),name='classviewdetails'),
    path('classviewupdate/<int:pk>/',views.TaskUpdateview.as_view(),name='classviewupdate'),
    path('classdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='classdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from django import forms
from .models import task
class TodoForm(forms.ModelForm):
    class Meta:
         model=task
         fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .models import task
from .forms import TodoForm
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class TaskListview(ListView):
    model=task;
    template_name = 'index.html'
    context_object_name = 'a'
class TaskDetailview(DetailView):
    model=task;
    template_name = 'details.html'
    context_object_name = 'b'
class TaskUpdateview(UpdateView):
    model=task;
    template_name = 'update.html'
    context_object_name = 'b'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todoapp:classviewdetails',kwargs={'pk':self.object.id})
class TaskDeleteview(DeleteView):
    model = task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:classviewhome')

def add(request):
    a=task.objects.all()
    if request.method =='POST':
        name=request.POST.get('taskname','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        tasks=task(name=name,priority=priority,date=date)
        tasks.save()
    return render(request,"index.html",{'a':a})
def details(request):
    tasks=task.objects.all()
    return render(request,'details.html',{'tasks':tasks})
def delete(request,taskid):
    if request.method=='POST':
        a = task.objects.get ( id=taskid)
        a.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    b=task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=b)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'b':b})




# Create your views here.

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure to delete this task?</p>
    <input type="submit">
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-tittle">{{b.name}}</h5>
                    <p><b>{{b.priority}}</b></p>
                    <p><b>{{b.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' b.id %}">Done</a>
                     <a class="btn btn-success" href="{% url 'todoapp:update' b.id %}">Update</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ f.as_p }}
    <button type="submit">Edit</button>
</form>
{% endblock %}

todoproject/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
        <form method="POST" class="mb-3 shadow">
           {% csrf_token %}
            <div class="form-group">
              <input type="text" name="taskname"  class= "form-control" placeholder="EntertaskName">
            </div>
          <div class=form-group">
            <input type="text" name="priority" class=" form-control" placeholder="Enter priority">
          </div>
            <div class=form-group">
              <input type="date" name="date" class=" form-control" placeholder="Enter Date">
          </div>
                <input type="Submit" class="btn btn-success">
        </form>
        </div>
        <div class ='col-md-6'>
            {% for i in a %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-tittle">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                     <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="class-title">
            TaskUpdate
        </div>
      <div class="card-body">
          <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
</form>
      </div>
"
    </div>
</div>
{% endblock %}