project2/movieapp/urls.py
from .import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('',views.reg,name='reg'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:id>/',views.update,name='update'),
    path ('delete/<int:id>/', views.delete, name='delete')

]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
    path ('shop/',include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project2/shop/urls.py
from .import views
from django.urls import path
app_name='shop'
urlpatterns = [
    path('',views.shopreg,name='shopreg'),
    path('mobadd/',views.mob_add,name='mob_add'),
    path('mobile/<int:mobid>/',views.mobdetail,name='mobdetail'),
    path ('update/<int:id>/' ,views.update , name='update'),
    path ('edit/<int:id>/' , views.edit , name='edit' ) ,
]

project2/movieapp/models.py
from django.db import models
class movie(models.Model):
    name=models.CharField(max_length=250)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name


# Create your models here.

project2/shop/models.py
from django.db import models
class mobile(models.Model):
    mobname=models.CharField(max_length=250)
    des=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.mobname
# Create your models here.

project2/movieapp/forms.py
from django import forms
from .models import movie
class MovieForm(forms.ModelForm):
    class Meta:
         model=movie
         fields=['name','des','year','img']

project2/shop/forms.py
from django import forms
from .models import mobile
class mobileform(forms.ModelForm):
    class Meta:
         model=mobile
         fields=['mobname','des','price','img']

project2/movieapp/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import movie
from .forms import MovieForm


# Create your views here.
def reg(request):
    movies=movie.objects.all()
    return render(request,'index.html',{'a':movies})

def detail(request,movie_id):
    x=movie.objects.get(id=movie_id)
    return render(request,"details.html",{'b':x})
def movie_add(request):
    if request.method == 'POST':
        name=request.POST.get('name',)
        des = request.POST.get('des',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        x=movie(name=name,des=des,year=year,img=img)
        x.save()
    return render(request,'add.html')

def update(request,id):
    y=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=y)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'y':y})
def delete(request,id):
    if request.method=="POST":
        y=movie.objects.get(id=id)
        y.delete()
        return redirect('/')
    return render(request,'delete.html')

project2/shop/views.py
from django.shortcuts import render,redirect
from .models import mobile
from .forms import mobileform
# Create your views here.
def shopreg(request):
    mob=mobile.objects.all()
    return render(request,'shopindex.html',{'mob':mob})
def mob_add(request):
    if request.method == 'POST':
        mobname=request.POST.get('mobname',)
        des = request.POST.get('des',)
        price = request.POST.get('price',)
        img = request.FILES['img']
        x=mobile(mobname=mobname,des=des,price=price,img=img)
        x.save()
    return render(request,'mobadd.html')
def mobdetail(request,mobid):
    x=mobile.objects.get(id=mobid)
    return render(request,"mobdetails.html",{'b':x})
def update(request,id):
    c = mobile.objects.get (id=id)
    if request.method == "POST":
      form =mobileform(request.POST,request.FILES,instance=c)
      if form.is_valid():
        form.save()
        return redirect ('/' )
    return render(request,'shopindex.html',{'c':c})
def edit(request,id):
    y = mobile.objects.get(id=id)
    form=mobileform(instance=y)
    return render(request,'update1.html',{'form':form,'y':y})

project2/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method ='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name"> <br>
    <input type="text" name="des" placeholder="Enter Movie description"> <br>
    <input type="text" name="year" placeholder="Enter Movie Year"> <br>
    <input type="file" name="img" placeholder="Enter movie Image"> <br>
    <input type="Submit">

</form>
</body>
</html>

project2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project2/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are You sure you want to delete this movie
    <input type="submit">
</form>

project2/templates/details.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
         <div class="col-md-4">
           <img src="{{b.img.url}}" height="300" width="300">
          </div>
     <div class="col-md-5">
        <h1> {{b.name}}</h1>
         <h5> {{b.des}}</h5>
          <h5> {{b.year}}</h5>
            <a class="btn btn-warning"href="{% url 'movieapp:update' b.id %}">Update</a>
            <a class="btn btn-danger"href="{% url 'movieapp:delete' b.id %}">Delete</a>
          </div>
    </div>
</div>
{% endblock %}

project2/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <input type="submit">
</form>

project2/templates/index.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
  <div class="row">
    {% for i in a %}
    <div class="col-md-3">
       <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"height="300px" width="300px">
       <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
<!--          <p class="card-text">{{i.des}}</p>-->
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go</a>
       </div>
     </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

project2/templates/mobadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method ='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="mobname" placeholder="Enter Mobile name"> <br>
    <input type="text" name="des" placeholder="Enter Specifications"> <br>
    <input type="text" name="price" placeholder="Enter price"> <br>
    <input type="file" name="img" placeholder="Enter mobile Image"> <br>
    <input type="Submit">

</form>
</body>
</html>

project2/templates/mobdetails.html
{% extends 'shopbase.html'%}
{% block body %}
<div class="container">
    <div class="row">
         <div class="col-md-4">
           <img src="{{b.img.url}}" height="300" width="300">
          </div>
     <div class="col-md-5">
        <h1> {{b.name}}</h1>
         <h5> {{b.des}}</h5>
          <h5> {{b.price}}</h5>
           <a class="btn btn-warning" href="{% url 'shop:edit' b.id %}">Edit</a>
          </div>
    </div>
</div>
{% endblock %}

project2/templates/mobedit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    {{form.as_p}}
  Details are updated
    <a class="btn btn-warning" href="{% url 'shop:mobdetail' c.id %}">Edit</a>
</form>

project2/templates/shopbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mobstyle.css'%}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-primary">
  <a class="navbar-brand" href="#">
    Online Mobile Shop
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project2/templates/shopindex.html
{% extends 'shopbase.html'%}
{% block body %}
<div class="container">
  <div class="row">
    {% for i in mob %}
    <div class="col-md-3">
       <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"height="300px" width="300px">
       <div class="card-body">
          <h5 class="card-title">{{i.mobname}}</h5>
<!--          <p class="card-text">{{i.des}}</p>-->
          <p class="card-text"><small class="text-muted">{{i.price}}</small></p>
          <a href="{% url 'shop:mobdetail' i.id %}" class="btn btn-primary">Specifications</a>&ndash;&gt
       </div>
     </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

project2/templates/update1.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <a class="btn btn-warning" href="{% url 'shop:update' y.id %}">update</a>
</form>